[package]
name = "libpwquality-sys"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Native bindings to the libpwquality library"
repository = "https://github.com/nibon7/libpwquality-rs"
links = "pwquality"
build = "build.rs"
exclude = [
  "libpwquality/doc/*",
  "libpwquality/po/*",
  "libpwquality/python/*",
]

[lib]
name = "libpwquality_sys"
path = "lib.rs"

[build-dependencies]
cc = "1.0"

[features]
default = [ "vendored"]
vendored = []
crack = []
