name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '00 04 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Install build dependencies
      run: sudo apt-get install -y libcrack2-dev

    - name: Clone libpwquality
      uses: actions/checkout@v4
      with:
          repository: 'libpwquality/libpwquality'
          path: 'thirdparty/libpwquality'

    - name: Build libpwquality
      run: |
        cd thirdparty/libpwquality/src
        touch config.h
        cc check.c error.c generate.c settings.c -I. -D"_(msgid)=(msgid)" -D_GNU_SOURCE -DHAVE_CRACK_H -lcrack -fPIC -shared -o libpwquality.so
        sed -e 's#@prefix@#/usr#' -e 's#@libdir@#/usr/lib#' -e 's#@exec_prefix@#${prefix}#' -e 's#@includedir@#${prefix}/include#' -e 's#@PACKAGE_VERSION@#1.4.5#' pwquality.pc.in > pwquality.pc
        sudo install -m0644 pwquality.pc /usr/share/pkgconfig/pwquality.pc
        sudo install -m0644 libpwquality.so /usr/lib/
        sudo install -m0644 pwquality.h /usr/include/

    - name: Rustfmt
      run: cargo fmt --all -- --check

    - name: Clippy
      run: cargo clippy --workspace --all-features --all-targets --examples --tests -- -D warnings

    - name: Test
      run: cargo test --workspace --all-features --all-targets --examples
