name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '00 04 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Install build dependencies
      run: sudo apt-get install -y cracklib-runtime

    - name: Rustfmt
      run: cargo fmt --all -- --check

    - name: Clippy
      run: cargo clippy --workspace --all-features --all-targets --examples --tests -- -D warnings

    - name: Test
      run: cargo test --workspace --all-features --all-targets --examples

    - name: Install cargo-valgrind
      run: |
        sudo apt-get install -y valgrind
        cargo install cargo-valgrind

    - name: Valgrind
      run: |
        ulimit -n 1024
        cargo valgrind run --all-features --example example
        cargo valgrind test --workspace --all-features --all-targets --examples
