name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '00 04 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Install build dependencies
      run:
        sudo apt-get install -y libpwquality-dev

    - name: Rustfmt
      run: cargo fmt --all -- --check

    - name: Clippy
      run: cargo clippy --workspace --features=v1_4_3 --all-targets --examples --tests -- -D warnings

    - name: Test
      run: cargo test --workspace --features=v1_4_3 --all-targets --examples
