name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly

      - name: Install build dependencies
        run: sudo apt-get install -y cracklib-runtime

      - name: Build Documentation
        env:
          RUSTDOCFLAGS: "--cfg docsrs"
        run: cargo +nightly doc --all-features --no-deps

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './target/doc/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
